[package]
name = "ruxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catppuccin = "2.2.0"
eframe = "0.27.1"
egui = "0.27.1"
image = "0.25.1"
rayon = "1.10.0"
rfd = "0.14.1"